# Generated by Django 3.0.7 on 2021-04-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tranaction_id',
            new_name='transaction_id',
        ),
    ]
