# Generated by Django 3.0.7 on 2021-04-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210427_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
    ]
